# https://giscus.app
# https://github.com/badboy/mdbook-mermaid

[book]
title = "凹语言™"
authors = ["柴树杉", "丁尔男", "史斌"]
description = "专注于 WASM 平台的通用编程语言"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
additional-css = ["static/css/style.css", "static/css/asciinema-player.css"]
additional-js = ["static/js/custom.js", "static/js/bigPicture.js", "static/js/asciinema-player.js"]
git-repository-url = "https://github.com/wa-lang/wa"
edit-url-template = "https://github.com/wa-lang/wa-lang.github.io/edit/master/{path}"
git-repository-icon = "fa-github"
