name: Deploy

on:
  push:
    branches:
      # - master
      - feat/new-website
  pull_request:
    branches:
      # - master
      - feat/new-website
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install Pkg
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.WA_DEPLOY }}
          publish_dir: docs/.vitepress/dist
          publish_branch: new-website
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
